[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./checkout"
healthcheckPath = "/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
GOGC = "50"
GOMEMLIMIT = "800MiB"
PORT = "5001"
